version: '2.1'
services:
  tenderapp:
    build: ./tendermint
    environment:
      APP_ENV: "development"
    volumes:
      - ${PWD-.}/data/tendermint:/tendermint
      # - ${PWD-.}/config/ethereum/dev/password:/root/files/password:ro
      # - ${PWD-.}/config/ethereum/dev/genesis.json:/root/files/genesis.json:ro
      # - ${PWD-.}/config/ethereum/dev/keystore:/root/.ethereum/devchain/keystore:rw