version: "2.1"
services:
  tendermaster:
    extends:
      file: docker-compose-common.yml
      service: tenderapp
    environment:
      ETHERMINT_ADDR: "tcp://ethermaster:46658"
      SEEDS: "tenderslave:46656"
    volumes:
      - ${PWD-.}/data/tendermaster:/tendermint
      - ${PWD-.}/tendermint/start.sh:/tendermint/start.sh:ro
    entrypoint: ""
    command: "/bin/sh /tendermint/start.sh"
    # hostname required for monitoring script
    hostname: tendermaster
    ports:
      - "46656:46656"
      - "46657:46657"
      - "30303:30303"
      - "30303:30303/udp"

  tenderslave:
    extends:
      file: docker-compose-common.yml
      service: tenderapp
    environment:
      ETHERMINT_ADDR: "tcp://etherslave:46658"
      # See https://github.com/tendermint/tendermint/blob/master/docs/deploy-testnets.rst
      SEEDS: "tendermaster:46656"
    volumes:
      - ${PWD-.}/data/tenderslave:/tendermint
      - ${PWD-.}/tendermint/start.sh:/tendermint/start.sh:ro
    entrypoint: ""
    command: "/bin/sh /tendermint/start.sh"
    # hostname required for monitoring script
    hostname: tenderslave

  ethermaster:
    extends:
      file: docker-compose-common.yml
      service: etherapp
    environment:
      TENDERMINT_ADDR: "tcp://tendermaster:46657"
      DATA_ROOT: "/ethermint"
    volumes:
      - ${PWD-.}/data/ethermaster:/ethermint
      - ${PWD-.}/ethermint/start.sh:/ethermint/start.sh:ro
    # Note: The password for the default account is 1234
    entrypoint: ""
    command: "/bin/sh /ethermint/start.sh"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "46658:46658"

  etherslave:
    extends:
      file: docker-compose-common.yml
      service: etherapp
    environment:
      TENDERMINT_ADDR: "tcp://tenderslave:46657"
      DATA_ROOT: "/ethermint"
    volumes:
      - ${PWD-.}/data/etherslave:/ethermint
      - ${PWD-.}/ethermint/start.sh:/ethermint/start.sh:ro
    entrypoint: ""
    command: "/bin/sh /ethermint/start.sh"

  # We need vanilla ethereum node for some utilities like `bootnode`
  ethutils:
    extends:
      file: docker-compose-common.yml
      service: vanilla_eth
    command: bash

  # Vanila geth, connects to Ethermint by default
  geth:
    extends:
      file: docker-compose-common.yml
      service: vanilla_eth
    entrypoint: geth
    command: attach http://ethermaster:8545
    depends_on:
      - ethermaster

  netstats:
    build: netstats
    restart: on-failure
    environment:
      - WS_SECRET=eth-net-stats-secret
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
