version: '2.1'
services:
  tenderapp:
    image: 'ld100/tendermint:alpine'
    # build: ./tendermint
    environment:
      APP_ENV: "development"
      ETHERMINT_ADDR: "tcp://ethermint:46658"
    # volumes:
    #   - ${PWD-.}/data/tendermint:/tendermint

  etherapp:
    image: 'ld100/ethermint:alpine'
    # build: ./ethermint
    environment:
      APP_ENV: "development"
      TENDERMINT_ADDR: "tcp://tendermint:46657"
      DATA_ROOT: "/ethermint"
    volumes:
      # - ${PWD-.}/data/ethermint:/ethermint
      - ${PWD-.}/setup/genesis.json:/ethermint/genesis.json:ro
      - ${PWD-.}/setup/bootnode.key:/ethermint/bootnode.key:ro
      - ${PWD-.}/setup/keystore:/ethermint/keystore:rw

  vanilla_eth:
    image: 'ld100/ethereum:alpine'
    # build: ./ethereum
    environment:
      APP_ENV: development
      DATA_ROOT: /root/.ethereum
    volumes:
     - ${PWD-.}/data/ethereum:/root/.ethereum
     - ${PWD-.}/setup/genesis.json:/root/.ethereum/genesis.json:ro

  truffleapp:
    build: ./contracts
    volumes:
      - ${PWD-.}/contracts:/usr/src/app
    environment:
      ETHEREUM_NETWORK: 'development'
      ETHEREUM_RPC_HOST: "ethermaster"
      ETHEREUM_DEPLOYER_ADDRESS: "0x7eff122b94897ea5b0e2a9abf47b86337fafebdc"
      ETHEREUM_DEPLOYER_PASSPHRASE: "1234"
      ETHEREUM_RPC_PORT: 8545
      ETHEREUM_UNLOCK_DURATION: 1800

